/**
 * fillPdfTemplate.ts
 *
 * Fills a PDF form template generated by convert_sheet_to_form.py.
 *
 * Field types:
 *  - txt / ml / date  → AcroForm TextField  (set via pdf-lib form API)
 *  - chk              → AcroForm CheckBox
 *  - sig / photo      → NO AcroForm widget — image drawn directly at rect
 *
 * Coordinate system note:
 *   PyMuPDF uses top-left origin.  pdf-lib uses bottom-left origin.
 *   Conversion:  pdfLibY = pageHeight - fieldmapY1
 */

import { PDFDocument } from 'pdf-lib'

// ── Types ──────────────────────────────────────────────────────────────────

export interface FieldInfo {
  type: 'txt' | 'ml' | 'chk' | 'sig' | 'date' | 'photo'
  page: number                               // 0-based page index
  rect: [number, number, number, number]     // [x0, y0, x1, y1] top-left origin (pts)
  fontsize: number
  font: string
  align: number                              // 0=left, 1=center, 2=right
  lines: number | null
  lineSpacing: number | null
}

export type FieldMap = Record<string, FieldInfo>

/**
 * Values to fill into each named field.
 *
 * - txt / ml / date  →  string
 * - chk              →  boolean | 'true' | 'false' | '1' | '0'
 * - sig / photo      →  URL string  OR  base64 data URL  (jpeg / png)
 *                       Pass null / undefined to leave the field empty.
 */
export type FieldValues = Record<string, string | boolean | null | undefined>

// ── Main entry ─────────────────────────────────────────────────────────────

/**
 * Fetches the PDF template and fieldmap, fills all fields, returns filled bytes.
 *
 * @param templateUrl   URL to the *_form.pdf  (R2 / CDN / local)
 * @param fieldmapUrl   URL to the *_fieldmap.json
 * @param values        Map of field name → value
 * @returns             Uint8Array of the filled PDF
 *
 * @example
 * ```ts
 * const bytes = await fillPdfTemplate(
 *   'https://r2.example.com/templates/itr_form.pdf',
 *   'https://r2.example.com/templates/itr_fieldmap.json',
 *   {
 *     projectName: 'Offshore Platform A',
 *     inspectionDate: '2025-06-15',
 *     accepted: true,
 *     signatureInspector: photoDataUrl,   // base64 png
 *     sitePhoto1: 'https://storage/img.jpg',
 *   }
 * )
 * // Save or display
 * const blob = new Blob([bytes], { type: 'application/pdf' })
 * window.open(URL.createObjectURL(blob))
 * ```
 */
export async function fillPdfTemplate(
  templateUrl: string,
  fieldmapUrl: string,
  values: FieldValues,
): Promise<Uint8Array> {
  // 1. Fetch template + fieldmap in parallel
  const [pdfBuffer, fieldmap] = await Promise.all([
    fetch(templateUrl).then(r => {
      if (!r.ok) throw new Error(`PDF fetch failed: ${r.status} ${templateUrl}`)
      return r.arrayBuffer()
    }),
    fetch(fieldmapUrl).then(r => {
      if (!r.ok) throw new Error(`Fieldmap fetch failed: ${r.status} ${fieldmapUrl}`)
      return r.json() as Promise<FieldMap>
    }),
  ])

  // 2. Load with pdf-lib
  const pdfDoc = await PDFDocument.load(pdfBuffer, { ignoreEncryption: true })
  const form   = pdfDoc.getForm()
  const pages  = pdfDoc.getPages()

  // 3. Fill each field
  for (const [name, info] of Object.entries(fieldmap)) {
    const value = values[name]
    if (value === undefined || value === null) continue

    const pageObj     = pages[info.page]
    if (!pageObj) {
      console.warn(`fillPdfTemplate: page ${info.page} not found for field "${name}"`)
      continue
    }
    const { height: pageH } = pageObj.getSize()

    // Convert PyMuPDF rect (top-left origin) → pdf-lib (bottom-left origin)
    const [x0, y0, x1, y1] = info.rect
    const pdfX = x0
    const pdfY = pageH - y1  // flip: pdf-lib Y is from bottom
    const w    = x1 - x0
    const h    = y1 - y0

    try {
      switch (info.type) {
        // ── Image fields (photo / sig) ─────────────────────────────────────
        case 'photo':
        case 'sig': {
          if (typeof value !== 'string' || !value) break
          const imgBytes = await fetchImageAsBytes(value)
          const ispng    = isPng(value, imgBytes)
          const img      = ispng
            ? await pdfDoc.embedPng(imgBytes)
            : await pdfDoc.embedJpg(imgBytes)
          // Scale to fit inside rect, preserving aspect ratio
          const dims = img.scaleToFit(w, h)
          // Center within the rect
          const dx = (w - dims.width)  / 2
          const dy = (h - dims.height) / 2
          pageObj.drawImage(img, {
            x:      pdfX + dx,
            y:      pdfY + dy,
            width:  dims.width,
            height: dims.height,
          })
          break
        }

        // ── Checkbox ───────────────────────────────────────────────────────
        case 'chk': {
          const cb = form.getCheckBox(name)
          const on = value === true || value === 'true' || value === '1'
          on ? cb.check() : cb.uncheck()
          break
        }

        // ── Text fields (txt / ml / date) ──────────────────────────────────
        case 'txt':
        case 'ml':
        case 'date':
        default: {
          form.getTextField(name).setText(String(value))
          break
        }
      }
    } catch (e) {
      console.warn(`fillPdfTemplate: could not fill field "${name}" (type=${info.type})`, e)
    }
  }

  return pdfDoc.save()
}

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Fetches an image from a URL or base64 data-URL and returns raw bytes.
 */
async function fetchImageAsBytes(src: string): Promise<Uint8Array> {
  if (src.startsWith('data:')) {
    // data:[mime];base64,<data>
    const comma = src.indexOf(',')
    if (comma === -1) throw new Error('Invalid data URL')
    const b64  = src.slice(comma + 1)
    const bin  = atob(b64)
    const buf  = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i)
    return buf
  }
  const res = await fetch(src)
  if (!res.ok) throw new Error(`Image fetch failed: ${res.status} ${src}`)
  return new Uint8Array(await res.arrayBuffer())
}

/**
 * Detects PNG by magic bytes (‰PNG) or data-URL mime type.
 * Falls back to JPEG assumption.
 */
function isPng(src: string, bytes: Uint8Array): boolean {
  if (src.startsWith('data:image/png')) return true
  if (src.toLowerCase().endsWith('.png'))  return true
  // PNG magic: 0x89 0x50 0x4E 0x47
  return bytes.length >= 4 &&
    bytes[0] === 0x89 && bytes[1] === 0x50 &&
    bytes[2] === 0x4E && bytes[3] === 0x47
}

// ── Convenience: open filled PDF in new tab ────────────────────────────────

/**
 * Fills the template and opens the result in a new browser tab.
 * Useful for quick preview / print.
 */
export async function previewFilledPdf(
  templateUrl: string,
  fieldmapUrl: string,
  values: FieldValues,
): Promise<void> {
  const bytes = await fillPdfTemplate(templateUrl, fieldmapUrl, values)
  const blob  = new Blob([bytes], { type: 'application/pdf' })
  const url   = URL.createObjectURL(blob)
  window.open(url, '_blank')
}

/**
 * Fills the template and triggers a browser download.
 */
export async function downloadFilledPdf(
  templateUrl: string,
  fieldmapUrl: string,
  values: FieldValues,
  filename = 'filled.pdf',
): Promise<void> {
  const bytes = await fillPdfTemplate(templateUrl, fieldmapUrl, values)
  const blob  = new Blob([bytes], { type: 'application/pdf' })
  const url   = URL.createObjectURL(blob)
  const a     = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 10_000)
}
